# This workflow automatically tests new commits and pull requests as they come in.
# Note that this does not upload any artifacts, you will need to compile mcMMO manually
# if you wish to create the actual jar.
name: Compile and test

on: [push]

jobs:
  compile:
    name: Maven compiler
    runs-on: ubuntu-latest
    steps:

    # 1. Check out the current working tree
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Setup Java 17 JDK (Adopt)
    - name: Java 17 setup
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-package: jdk
        java-version: '17'

    # 3. Setup local Maven package cache to speed up building
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    # 4. Build via Maven 
    - name: Build via Maven
      run: mvn verify -B --file pom.xml -DdisableXmlReport=true
      
    # 5. Upload artefact
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: "McMMO"
        path: "McMMO"
